home:
  path: /
  controller: App\Controller\RecipeController::index

recipe.index:
  path: /recette/lister
  controller: App\Controller\RecipeController::index

recipe.show:
  path: /recette/{slug}-{id}
  requirements: 
    slug: '[a-z0-9\-]*'
  controller: App\Controller\RecipeController::show
  methods: GET

recipe.create:
  path: /member/recette/creer
  controller: App\Controller\CrudRecipeController::create

recipe.edit:
  path: /member/recette/{id}
  controller: App\Controller\CrudRecipeController::edit
  methods: GET|POST

recipe.delete:
  path: /member/recette/{id}
  controller: App\Controller\CrudRecipeController::delete
  methods: DELETE

recipe.favoris:
  path: /member/recette/togglefav/{id}
  controller: App\Controller\CrudRecipeController::toggleFav
  methods: GET

comment.create:
  path: /member/recette/{slug}-{id}/comment/creer
  requirements: 
    slug: '[a-z0-9\-]*'
  controller: App\Controller\CrudCommentController::create
  methods: GET|POST

register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: GET|POST

login:
  path: /login
  controller: App\Controller\SecurityController::login

login.google:
  path: /login/google
  controller: App\Controller\GoogleController::connectAction

connect.google.check:
  path: /connect/google/check
  controller: App\Controller\GoogleController::connectCheckAction

logout:
  path: /logout

account.activation:
  path: /activation/{code}
  controller: App\Controller\RegistrationController::activation

login.forget:
  path: /login/forget
  controller: App\Controller\SecurityController::forgetPassword

login.reset:
  path: /login/reset/{code}
  controller: App\Controller\SecurityController::resetPassword