home:
  path: /
  controller: App\Controller\RecipeController::index

recipe.index:
  path: /recette/lister
  controller: App\Controller\RecipeController::index

recipe.show:
  path: /recette/{slug}-{id}
  requirements: 
    slug: '[a-z0-9\-]*'
  controller: App\Controller\RecipeController::show

recipe.create:
  path: /admin/recette/creer
  controller: App\Controller\CrudRecipeController::create

recipe.edit:
  path: /admin/recette/{id}
  controller: App\Controller\CrudRecipeController::edit
  methods: GET|POST

recipe.delete:
  path: /admin/recette/{id}
  controller: App\Controller\CrudRecipeController::delete
  methods: DELETE

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
